title: Music Scheduler Deadlines
description: Countdowns to Music deadlines
author: Hsiang Nianian

domain: ""
baseurl: "https://hsiangnianian.github.io/ai-deadlines/"

twitter_hashtag: HsiangNianian
github_username: HsiangNianian
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
